### ISSUE TITLE
Feature request: text and HTML output

### ISSUE THREAD

**Issue by FedericoCeratto** [yglukhov/coverage#2]
Thanks for  developing coverage!
It would be very nice to have a text and HTML output showing the non-covered lines.

**Comment by yglukhov** [comment]
There is a crude html report generator:

``` sh
export NIM_COVERAGE_DIR=coverage_results
mkdir -p "$NIM_COVERAGE_DIR"

nim c -r unittests.nim # This is your program that uses coverage.
nimcoverage genreport # nimcoverage is installed in nimble/bin
```

After this you'll get your coverage report in coverage_results dir. Please feel free to contribute! ;)
