### ISSUE TITLE
Cannot install it on Nim 0.19.9

### ISSUE THREAD

**Issue by narimiran** [yglukhov/coverage#6]
The output of `nimble install coverage`:

```
      ... coverage.nim(255, 53) Error: type mismatch: got <string, multipart: MultipartData>
        ... but expected one of: 
        ... proc postContent(client: HttpClient; url: string; body = "";
        ...                 multipart: MultipartData = nil): string
        ...   first type mismatch at position: 1
        ...   required type: HttpClient
        ...   but expression '"https://coveralls.io/api/v1/jobs"' is of type: string
        ... proc postContent(client: AsyncHttpClient; url: string; body = "";
        ...                 multipart: MultipartData = nil): Future[string]
        ...   first type mismatch at position: 1
        ...   required type: AsyncHttpClient
        ...   but expression '"https://coveralls.io/api/v1/jobs"' is of type: string
        ... expression: postContent("https://coveralls.io/api/v1/jobs", multipart = data)
```

It is because 0.19.9 has removed the deprecated version (since v0.15) of `postContent` proc.

**Comment by develooper1994** [comment]
nim==0.20.0
output:
     Error: Build failed for package: coverage
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "C:\nim\bin\nim.exe" c --noBabelPath -d:release --path:"C:\Users\selcu\.nimble\pkgs\nake-1.9.3"  -o:"C:\Users\selcu\AppData\Local\Temp\nimble_7756\githubcom_yglukhovcoverage\nimcoverage.exe" "C:\Users\selcu\AppData\Local\Temp\nimble_7756\githubcom_yglukhovcoverage\nimcoverage.nim"
        ... Output: Hint: used config file 'C:\nim\config\nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: widestrs [Processing]
        ... Hint: io [Processing]
        ... Hint: nimcoverage [Processing]
        ... Hint: coverage [Processing]
        ... Hint: macros [Processing]
        ... Hint: tables [Processing]
        ... Hint: hashes [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: os [Processing]
        ... Hint: pathnorm [Processing]
        ... Hint: osseps [Processing]
        ... Hint: winlean [Processing]
        ... Hint: dynlib [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: time_t [Processing]
        ... Hint: osproc [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: json [Processing]
        ... Hint: lexbase [Processing]
        ... Hint: parsejson [Processing]
        ... Hint: httpclient [Processing]
        ... Hint: net [Processing]
        ... Hint: nativesockets [Processing]
        ... Hint: sets [Processing]
        ... Hint: uri [Processing]
        ... Hint: base64 [Processing]
        ... Hint: mimetypes [Processing]
        ... Hint: random [Processing]
        ... Hint: httpcore [Processing]
        ... Hint: asyncnet [Processing]
        ... Hint: asyncdispatch [Processing]
        ... Hint: heapqueue [Processing]
        ... Hint: lists [Processing]
        ... Hint: asyncstreams [Processing]
        ... Hint: asyncfutures [Processing]
        ... Hint: deques [Processing]
        ... Hint: cstrutils [Processing]
        ... Hint: asyncfile [Processing]
        ... Hint: md5 [Processing]
        ... C:\Users\<user>\AppData\Local\Temp\nimble_7756\githubcom_yglukhovcoverage\coverage.nim(175, 13) Hint: 'covDir' is declared but not used [XDeclaredButNotUsed]
        ... C:\Users\<user>\AppData\Local\Temp\nimble_7756\githubcom_yglukhovcoverage\coverage.nim(255, 53) Error: type mismatch: got <string, multipart: MultipartData>
        ... but expected one of:
        ... proc postContent(client: HttpClient; url: string; body = "";
        ...                 multipart: MultipartData = nil): string
        ...   first type mismatch at position: 1
        ...   required type: HttpClient
        ...   but expression '"https://coveralls.io/api/v1/jobs"' is of type: string
        ... proc postContent(client: AsyncHttpClient; url: string; body = "";
        ...                 multipart: MultipartData = nil): Future[string]
        ...   first type mismatch at position: 1
        ...   required type: AsyncHttpClient
        ...   but expression '"https://coveralls.io/api/v1/jobs"' is of type: string
        ... expression: postContent("https://coveralls.io/api/v1/jobs", multipart = data)

**Comment by yglukhov** [comment]
Fixed.
